# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"assert_allclose": "utils.ipynb",
         "get_colors": "utils.ipynb",
         "get_notebook_file": "utils.ipynb",
         "save_notebook": "utils.ipynb",
         "build_notebook": "utils.ipynb",
         "convert_notebook": "utils.ipynb",
         "MyDisjointSet": "module3.ipynb",
         "MyDisjointSet2": "module3.ipynb",
         "MyDisjointSet3": "module3.ipynb",
         "rgb2gray": "utils.ipynb",
         "DisjointSetsForest": "module3.ipynb",
         "DisjointSetsPathCompression": "module3.ipynb",
         "DisjointSetsTwoPassPC": "module3.ipynb",
         "DisjointSetsMergeByHeight": "module3.ipynb",
         "DisjointSetsMergeByHeight2": "module3.ipynb",
         "DisjointSetsMergeByHeight3": "module3.ipynb",
         "DisjointSetsMergeByWeight": "module3.ipynb",
         "DisjointSetsMergeByHeightAndPathCompression": "module3.ipynb",
         "DisjointSetsMergeByHeightAndPathCompression2": "module3.ipynb",
         "Node": "module6.ipynb",
         "LinkedList": "module6.ipynb",
         "bs": "module6.ipynb",
         "sed_slow": "module10.ipynb",
         "sed_fast": "module10.ipynb",
         "seam_removal": "seamcarving.ipynb"}

modules = ["utils.py",
           "module3.py",
           "hw1.py",
           "module5.py",
           "hw2.py",
           "module6.py",
           "module10.py",
           "module11.py",
           "seamcarving.py",
           "hw3.py",
           "module13.py",
           "module14.py",
           "module16.py",
           "module17.py"]

doc_url = "https://justinblaber.github.io/cs371/"

git_url = "https://github.com/justinblaber/cs371/tree/master/"

def custom_doc_links(name): return None
